<?php
/**
 * @file
 * Overrides the default functionality, by Metal Toad
 *
 */

 function bef_misc_form_alter(&$form, &$form_state, $form_id) {
  // this is for your developer information and shows you the
  // structure of the form array
  dpm($form);
  // Changes the Page Title of the form used to add "Activity" content type
  if ($form_id == 'activity_node_form') {
    drupal_set_title(t('Upload New Teacher Activity'));
  }
  // On the activity_node_form, moves the descriptor text from below the input fields to above the input fields. 
  if ($form_id == 'case_history_node_form')
	$form['field_activity']['und']['#description'] = 'Hello Toon Town!';
}